# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4c44eedbb08b6dc43c44e24f74831d688f0dfbfb74d2c76c01c80819c97f4b38531b5276236a5c5b65d392e253080435697b2ec0707a840860d00dcb8cecad6

test:
  secret_key_base: 86b4dbd44fb4ad778026d789e3d08b496232e1c36c71864d8c4709a647d571556955a38bd0dda6be9683f6eea90f474efab88fa6e4bb3c5fedbaba1b5f44a9af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
